services:
  web:
    build:
      context: .
      args:
        - SERVICE_NAME=${SERVICE_NAME}
        - CONTAINER_PORT=${CONTAINER_PORT}
        - MAIN_DOMAIN=${MAIN_DOMAIN}
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    ports:
      - "${HOST_IP}:${HOST_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - CONTAINER_PORT=${CONTAINER_PORT}
    env_file:
      - .prod.env
    volumes:
      - olympiad_db_data:/var/lib/olympiad-api/db

volumes:
  olympiad_db_data: